---
# handlers file for roles/deployAppPhp


- name: restart apache2
  service:
    name: apache2
    state: restarted
  become: true

- name: restart phpfpm
  service:
    name: php-fpm7
    state: restarted
  become: true

- name : restart phpfpm2
  service:
    name: php7.3-fpm
    state: restarted
  become: true

- name : restart mariadb
  service:
    name: mariadb
    state: restarted
  become: true

- name : restart redis
  service:
    name: redis
    state: restarted
  become: true 
